const express = require('express');
const inventory = express.Router();
const inventoryController = require('../controller/inventorycontroller/inventorycontroller');
const { verifytoken,isFrontdesk } = require('../middleware/auth');

inventory.get('/', verifytoken,isFrontdesk,inventoryController.dashboard);
inventory.get('/products',verifytoken,isFrontdesk, inventoryController.productsPage);
inventory.get('/products/template.csv',verifytoken,isFrontdesk,inventoryController.downloadProductTemplate);
inventory.post('/products/import-csv',verifytoken,isFrontdesk,inventoryController.importProductsCsv);
inventory.post('/products',verifytoken,isFrontdesk, inventoryController.createProduct);
inventory.post('/products/save',verifytoken,isFrontdesk, inventoryController.saveProducts);
inventory.get('/categories',verifytoken,isFrontdesk, inventoryController.categoriesPage);
inventory.post('/categories',verifytoken,isFrontdesk, inventoryController.createCategory);
inventory.post('/categories/:id/edit',verifytoken,isFrontdesk, inventoryController.editCategory);
inventory.post('/categories/:id/delete',verifytoken,isFrontdesk, inventoryController.deleteCategory);
inventory.get('/quantity-types',verifytoken,isFrontdesk, inventoryController.quantityTypesPage);
inventory.post('/quantity-types', verifytoken,isFrontdesk, inventoryController.createQuantityType);
inventory.post('/quantity-types/:id/edit', verifytoken,isFrontdesk, inventoryController.editQuantityType);
inventory.post('/quantity-types/:id/delete', verifytoken,isFrontdesk, inventoryController.deleteQuantityType);
inventory.get('/suppliers', verifytoken,isFrontdesk, inventoryController.suppliersPage);
inventory.post('/suppliers', verifytoken,isFrontdesk, inventoryController.createSupplier);
inventory.post('/suppliers/:id/edit',verifytoken,isFrontdesk, inventoryController.editSupplier);
inventory.post('/suppliers/:id/delete',verifytoken,isFrontdesk, inventoryController.deleteSupplier);
inventory.get('/sales/template.csv', verifytoken,isFrontdesk, inventoryController.downloadTransactionTemplate);
inventory.post('/sales/import-csv', verifytoken,isFrontdesk, inventoryController.importTransactionsCsv);
inventory.get('/sales', verifytoken,isFrontdesk, inventoryController.salesPage);
inventory.post('/sales', verifytoken,isFrontdesk, inventoryController.createTransaction);
inventory.get('/salesreturns', verifytoken,isFrontdesk, inventoryController.salesReturnsPage);
inventory.post('/salesreturns', verifytoken,isFrontdesk, inventoryController.createSalesReturn);
inventory.get('/purchasereturns', verifytoken,isFrontdesk, inventoryController.purchaseReturnsPage);
inventory.post('/purchasereturns', verifytoken,isFrontdesk, inventoryController.createPurchaseReturn);
inventory.get('/productrequests', verifytoken, inventoryController.productRequestsPage);
inventory.post('/productrequests', verifytoken, inventoryController.createProductRequest);
inventory.post('/productrequests/:id/review', verifytoken, inventoryController.requireInventoryManager, inventoryController.reviewProductRequest);
inventory.get('/search/products', verifytoken, inventoryController.searchRequestProducts);
inventory.get('/search/teachers', verifytoken, inventoryController.searchRequestTeachers);
inventory.get('/analytics',verifytoken,isFrontdesk, inventoryController.analyticsPage);
inventory.get('/search/assignees', verifytoken,isFrontdesk, inventoryController.searchAssignees);
inventory.get('/transactions/:id/print', verifytoken,isFrontdesk, inventoryController.printTransaction);

module.exports = inventory;